<?php

include APPLICATION_PATH.'/CreateImages.php';

function drawUser($id) {	
	return "<li><a href='/albums/index/user/$id' title='$id'><img src='/img/user.png' alt='$id' /></a></li>";
}

function drawIndex() {
	
	$path = realpath(APPLICATION_PATH . '/../public/users');

	if ($dir = opendir($path))
	{
		$userList = array();
		while (false !== ($user_rep = readdir($dir)))
		{
			if ($user_rep != "." && $user_rep != "..")
			{
				if (is_dir("users/" . $user_rep))
				{
					$userList[] = $user_rep;
				}
			}
		}
	}

	$html = <<<EOT
<div class='page-header'>
	<h2><a href='.' title='index'>home</a></h2>
</div>
<div class='content'>
	<ul class='polaroids'>
EOT;
	
	foreach($userList as $user)
	{
		$html .= drawUser($user);
	}
	
	$html .= <<<EOT
	</ul>
	<br class='clear'/>
</div>
</div>
EOT;

	return $html;
}

echo drawIndex();