<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>PHPic</title>
<?php 
echo $this->headLink()->appendStylesheet('/css/global.css');
echo $this->headLink()->appendStylesheet('/css/jquery.fancybox.css');
echo $this->headScript()->appendFile('/js/jquery.min.js', $type = 'text/javascript', $attrs = array());
echo $this->headScript()->appendFile('/js/jquery.fancybox.pack.js', $type = 'text/javascript', $attrs = array());
?>

</head>
<body>
<div class="site-container">
	<div class="header">
		<a class="brand" href="/"><img src="/img/logo.png" alt="PHPic"/></a>
		<div class="profile">
	<?php echo $this->profileLink() ?>
		</div>
	<br class='clear'/>
	</div>
	<div class="container">
		<?php echo $this->layout()->content ?>
	<br class='clear'/>
	<footer>
		<p>&copy; PHPic 2012</p>
	</footer>
</div>

</body>
</html>
