<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<title>PHPic</title>
<?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div class="header">
	<a class="brand" href="/">PHPic</a>
	<p>
<?php echo $this->profileLink() ?>
	</p>
</div>
<div class="container">
<?php echo $this->layout()->content ?>
<footer>
	<p>&copy; PHPic 2012</p>
</footer>
</div>
</body>
</html>
